inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/bundle'

Layout/EndAlignment:
  AutoCorrect: true

Layout/LineLength:
  Max: 200
  AutoCorrect: true

Layout/MultilineArrayLineBreaks:
  Enabled: true

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Exclude:
    - 'lib/intacct/models/**/*'

Style/ModuleFunction:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
